### ISSUE TITLE
Unable to sync notes

### ISSUE THREAD

**Issue by anLizard** [standardnotes/syncing-server#102]
docker-compose.yml:
```
version: "3"

networks:
  internal:
  caddy_external:
    external: true

services:    

  server:
    image: standardnotes/syncing-server
    networks:
      - internal
      - caddy_external
    expose:
      - 3000
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - db
    env_file:
      - .env
    #user: 1000:1000
    labels:
      - caddy=test.notes.$MY_DOMAIN
      - caddy.route=/api/*
      - caddy.route.0_uri=strip_prefix /api
      - caddy.route.1_reverse_proxy={{upstreams 3000}}

  db:
    image: linuxserver/mariadb
    networks:
      - internal
    restart: always
    volumes:
      - ./db:/config
    environment:
      - MYSQL_DATABASE=$DB_DATABASE
      - MYSQL_USER=$DB_USERNAME
      - MYSQL_PASSWORD=$DB_PASSWORD
      - MYSQL_ROOT_PASSWORD=$DB_ROOT_PASSWORD
      - PUID=1000
      - PGID=1000
      - TZ=CET
```

.env file:
```
MY_DOMAIN=example.com

# Rails Settings

EXPOSED_PORT=3000
RAILS_ENV=production
RAILS_LOG_TO_STDOUT=false

# Database Settings

DB_HOST=db
DB_PORT=3306

DB_DATABASE=standardnotes
DB_USERNAME=standardnotes
DB_PASSWORD=[redacted]
DB_ROOT_PASSWORD=[redacted]

#DB_POOL_SIZE=30
#DB_WAIT_TIMEOUT=180

# Standard Notes Settings

SECRET_KEY_BASE=[redacted]

DISABLE_USER_REGISTRATION=false
DATADOG_ENABLED=false

```

I can sign up on app.standardnotes.org using my sync server `test.notes.example.com/api`.
But any notes I create don't sync properly. It is stuck on `Syncing:0/1`, then creates duplicates of the note I created.

![image](https://user-images.githubusercontent.com/48686356/91757597-e1110200-ebce-11ea-8886-323c3de9f332.png)
![image](https://user-images.githubusercontent.com/48686356/91757549-c8a0e780-ebce-11ea-9771-a01798b058a9.png)

Logs for the syncing-server container:
```
server_1  | Starting Server...
server_1  | => Booting Puma
server_1  | => Rails 5.1.7 application starting in production
server_1  | => Run `rails server -h` for more startup options
server_1  | Puma starting in single mode...
server_1  | * Version 4.3.5 (ruby 2.6.5-p114), codename: Mysterious Traveller
server_1  | * Min threads: 5, max threads: 5
server_1  | * Environment: production
server_1  | * Listening on tcp://0.0.0.0:3000
server_1  | Use Ctrl-C to stop
server_1  | {"method":"POST","path":"/items/sync","format":"*/*","controller":"Api::ItemsController","action":"sync","status":200,"duration":60.52,"view":0.99,"db":6.9,"ddsource":["ruby"],"time":"2020-08-31 19:09:49 +0000","params":{"limit":150,"items":[{"uuid":"ba50f164-2d49-49fd-923d-0ca820c8b8fe","content_type":"[FILTERED]","created_at":"2020-08-31T19:08:57.885Z","updated_at":"1970-01-01T00:00:00.000Z","enc_item_key":"[FILTERED]","content":"[FILTERED]","auth_hash":"[FILTERED]"}],"sync_token":"MjoxNTk4OTAwOTQ4LjE0MjM3MDI=\n","cursor_token":null,"api":"20190520","controller":"api/items","action":"sync","item":{}},"level":"INFO"}
server_1  | {"method":"POST","path":"/items/sync","format":"*/*","controller":"Api::ItemsController","action":"sync","status":200,"duration":3.74,"view":0.18,"db":1.0,"ddsource":["ruby"],"time":"2020-08-31 19:09:50 +0000","params":{"limit":150,"items":[],"sync_token":"MjoxNTk4OTAwOTg5Ljg3Nzg0Ng==\n","cursor_token":null,"api":"20190520","controller":"api/items","action":"sync","item":{}},"level":"INFO"}
server_1  | {"method":"POST","path":"/items/sync","format":"*/*","controller":"Api::ItemsController","action":"sync","status":200,"duration":3.71,"view":0.2,"db":0.98,"ddsource":["ruby"],"time":"2020-08-31 19:09:50 +0000","params":{"limit":150,"items":[],"sync_token":"MjoxNTk4OTAwOTkwLjAxODQ2Mjc=\n","cursor_token":null,"api":"20190520","controller":"api/items","action":"sync","item":{}},"level":"INFO"}
server_1  | {"method":"POST","path":"/items/sync","format":"*/*","controller":"Api::ItemsController","action":"sync","status":200,"duration":3.7,"view":0.21,"db":0.97,"ddsource":["ruby"],"time":"2020-08-31 19:09:53 +0000","params":{"limit":150,"items":[],"sync_token":"MjoxNTk4OTAwOTkwLjM4ODg2NA==\n","cursor_token":null,"api":"20190520","controller":"api/items","action":"sync","item":{}},"level":"INFO"}
server_1  | {"method":"POST","path":"/items/sync","format":"*/*","controller":"Api::ItemsController","action":"sync","status":200,"duration":3.67,"view":0.19,"db":0.97,"ddsource":["ruby"],"time":"2020-08-31 19:09:55 +0000","params":{"limit":150,"items":[],"sync_token":"MjoxNTk4OTAwOTkzLjk0OTM5Mjg=\n","cursor_token":null,"api":"20190520","controller":"api/items","action":"sync","item":{}},"level":"INFO"}
```
