### ISSUE TITLE
[Help Wanted] Authentication Required after a certain time

### ISSUE THREAD

**Issue by davidrot** [standardnotes/syncing-server#159]
**Describe the issue**
I have a self hosted docker instance running with the latest version. I'm using a android client (latest) and a mac osx client (latest with brew). 
After a certain time I get the message authentication required. I havent restarted the server or added a new client. Sync was working.

**To Reproduce**
No steps known

**Expected behavior**
No authentication required dialog.

**Screenshots**
No screenshot, because of standard dialog

**Desktop (please complete the following information):**
 - OS: Mac OSx
 - Version 10.15.7

**Smartphone (please complete the following information):**
 - Device: Samsung
 - OS: Android
 - Version: latest

**Docker Log file:**
Here is a link to the docker log output: 
https://controlc.com/2fdd648c

**Docker-Compose**
```
services:
  mariadb:
    image: mariadb:10.3.12
    container_name: standardnotes-mariadb
    volumes:
      - ./mariadb-standardnotes:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=standard_notes_db
    restart: always
    labels:
      - traefik.backend=mariadb
    networks:
      - backend 

  standardnotes-server:
    command: start-local
    image: standardnotes/syncing-server:stable
    container_name: standardnotes-server
    depends_on:
      - mariadb
    env_file: standardnotes-syncing-server.env
    restart: unless-stopped
    environment:
      DB_HOST: mariadb
    labels:
      - "traefik.enable=true"
      ....
    networks:
      - proxy
      - backend
```
