### ISSUE TITLE
Bug: mysql environment variables are not populated in docker-compose.yml

### ISSUE THREAD

**Issue by dgraziotin** [standardnotes/syncing-server#171]
These environment variables:
```
environment:
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
```
are populated only when adding ```env_file: .env```before them. Otherwise they are empty and the database will not be accessed.
