### ISSUE TITLE
MySQL Access Denied for User Error

### ISSUE THREAD

**Issue by devgrips** [standardnotes/syncing-server#177]
I'm trying to start the app from compose file, however, it keeps restarting during data migration step with the error that MySQL can't access the std_notes_user. Here are the logs of syncing_app container:

```
Bundle complete! 30 Gemfile dependencies, 105 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
Prestart Step 3/4 - Migrating database
rails aborted!
Mysql2::Error: Access denied for user 'std_notes_user'@'172.19.0.4' (using password: YES)
/usr/local/bundle/gems/mysql2-0.4.10/lib/mysql2/client.rb:89:in `connect'
/usr/local/bundle/gems/mysql2-0.4.10/lib/mysql2/client.rb:89:in `initialize'
/usr/local/bundle/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/mysql2_adapter.rb:22:in `new'
/usr/local/bundle/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/mysql2_adapter.rb:22:in `mysql2_connection'
/usr/local/bundle/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:830:in `new_connection'
/usr/local/bundle/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:874:in `checkout_new_connection'
/usr/local/bundle/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:853:in `try_to_checkout_new_connection'
/usr/local/bundle/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:814:in `acquire_connection'
/usr/local/bundle/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:538:in `checkout'
/usr/local/bundle/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:382:in `connection'
/usr/local/bundle/gems/ar-octopus-0.10.2/lib/octopus/proxy.rb:73:in `safe_connection'
/usr/local/bundle/gems/ar-octopus-0.10.2/lib/octopus/proxy.rb:80:in `select_connection'
/usr/local/bundle/gems/ar-octopus-0.10.2/lib/octopus/proxy.rb:225:in `legacy_method_missing_logic'
/usr/local/bundle/gems/ar-octopus-0.10.2/lib/octopus/proxy.rb:131:in `method_missing'
/usr/local/bundle/gems/activerecord-5.2.4.4/lib/active_record/tasks/database_tasks.rb:172:in `migrate'
/usr/local/bundle/gems/activerecord-5.2.4.4/lib/active_record/railties/databases.rake:60:in `block (2 levels) in <main>'
/usr/local/bundle/gems/railties-5.2.4.4/lib/rails/commands/rake/rake_command.rb:23:in `block in perform'
/usr/local/bundle/gems/railties-5.2.4.4/lib/rails/commands/rake/rake_command.rb:20:in `perform'
/usr/local/bundle/gems/railties-5.2.4.4/lib/rails/command.rb:48:in `invoke'
/usr/local/bundle/gems/railties-5.2.4.4/lib/rails/commands.rb:18:in `<main>'
/usr/local/bundle/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/usr/local/bundle/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/usr/local/bundle/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/usr/local/bundle/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/usr/local/bundle/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
/usr/local/bundle/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:291:in `block in require'
/usr/local/bundle/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:257:in `load_dependency'
/usr/local/bundle/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:291:in `require'
bin/rails:4:in `<main>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```

**My .env file:** 

```
# Rails Settings
EXPOSED_PORT=3000
# change this to "production" for production use, otherwise the access token time is very short and forces re-login
RAILS_ENV=production
RAILS_LOG_TO_STDOUT=false
# Log Level options: "INFO" | "DEBUG" | "INFO" | "WARN" | "ERROR" | "FATAL"
RAILS_LOG_LEVEL=INFO
#SQS_QUEUE=somequeue
#SQS_QUEUE_LOW_PRIORITY=low_priority_queue
#AWS_REGION=us-west1
#S3_BACKUP_BUCKET_NAME=

ACTIVE_JOB_QUEUE_ADAPTER=async

# Database Settings
DB_PORT=3306
DB_HOST=db
DB_DATABASE=standard_notes_db
DB_USERNAME=std_notes_user
# Please change this!
DB_PASSWORD=mypassword
DB_POOL_SIZE=30
DB_WAIT_TIMEOUT=180

# Secrets
# Use: "bundle exec rake secret" or "openssl rand -hex 64"
# To generate required secret key base below

SECRET_KEY_BASE=mysecretkey
PSEUDO_KEY_PARAMS_KEY=mysecretkey

# Disable user registration
#DISABLE_USER_REGISTRATION=true

# Datadog
DATADOG_ENABLED=false

# Mailer settings
SMTP_HOST=
SMTP_PORT=
SMTP_USERNAME=
SMTP_PASSWORD=
SMTP_DOMAIN=
EMAIL_ATTACHMENT_MAX_SIZE=10485760

# SNS EVENTS
#SNS_TOPIC_ARN=

# (Optional) Database Replication
#DB_REPLICA_HOST=

# Revisions persistency
REVISIONS_FREQUENCY=300

# (Optional) Redis Cache for ephemeral sessions
#REDIS_URL=redis://cache:6379

# (Optional) Change URLs to Internal DNS
INTERNAL_DNS_REROUTE_ENABLED=false
```

**My compose file:**

```
version: '3.8'
services:
  app:
    build: .
    command: start-local
    env_file: .env
    restart: unless-stopped
    environment:
      DB_HOST: db
      REDIS_URL: redis://cache:6379
    ports:
      - 3000:${EXPOSED_PORT}
    networks:
      standardnotes_proxy:
        aliases:
          - syncing_server
      syncing_server: {}
    volumes:
      - .:/syncing-server

  db:
    image: mysql:5.6
    environment:
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
    expose:
      - 3306
    ports:
      - 3306
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci
    volumes:
      - ./data:/var/lib/mysql
    networks:
      - syncing_server

  cache:
    image: redis:6.0-alpine
    volumes:
      - ./cache:/data
    expose:
      - 6379
    ports:
      - 6379
    networks:
      - syncing_server

networks:
  syncing_server:
    name: syncing_server
  standardnotes_proxy:
    name: standardnotes
```

I already changed the DB_HOST to "db" and tried the solution in #20 but when I run volume rm command I get this output:

`Error: No such volume: syncingserver_std_notes_db`

So, am I doing something wrong? I don't understand because I was just following the official docs on docker setup but it never worked for me.
